server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456



  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 2


mybatis-plus:
  #config-location:  classpath:mybatis-config.xml
  check-config-location: false
  executor-type: reuse
  configuration:
    aggressive-lazy-loading: true
    lazy-loading-enabled: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    cache-enabled: true
    call-setters-on-nulls: false
  global-config:
    sql-parser-cache: true
    db-config:
      db-type: mysql
      id-type: id_worker
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true